/*
 * wlvision-fixture.c - the deterministic native-Wayland fixture application
 * driven by the Phase 5 integration gates.
 *
 * One binary, flags select the behaviour: cooperative/delayed/ignored/exit
 * resize handling, animation bursts with a minimum inter-frame period, a
 * quiet screen that maps and then stops committing, and optional keyboard and
 * pointer event reporting through the compositor's own xkb keymap.
 *
 * The pending-frame loop is prepared-read/poll based and driven by
 * wl_surface.frame callbacks, so it never sleeps: nothing is committed until
 * the compositor has presented the previous frame.  The poll timeout only
 * exists to enforce the animation period, the delayed-resize deadline and the
 * --exit-after deadline, including on a compositor that would otherwise stop
 * sending frame callbacks because nothing has changed.
 *
 * Every committed buffer is drawn deterministically: a fixed base colour plus,
 * with --animate, one solid rectangle whose position and colour are a pure
 * function of the frame index.  No randomness and no clock enter the pixels.
 *
 * The xdg-shell bindings are generated by wayland-scanner from
 * wayland-protocols at image build time (see Containerfile); the protocol XML
 * is not hand-rolled.
 *
 * Copyright (C) 2026 wlvision
 * SPDX-License-Identifier: MIT
 */

#define _GNU_SOURCE

#include <errno.h>
#include <getopt.h>
#include <poll.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/mman.h>

#include <wayland-client.h>
#include <xkbcommon/xkbcommon.h>
#include "xdg-shell-client-protocol.h"

#define REPORT_PREFIX  "wlvision-fixture: "
#define DEFAULT_TITLE  "wlvision-fixture"
#define DEFAULT_APP_ID "wlvision.fixture"

#define DEFAULT_WIDTH  320
#define DEFAULT_HEIGHT 240

#define BASE_COLOUR 0xff204080u

#define MAX_BUFFERS 256

/* How long a client that finished its frame budget waits for a resize
 * configure it was never sent before giving up, when --exit-after is 0. */
#define ANIMATION_GRACE_MS 1000

/* Longest poll timeout: wake up at least once a second so deadlines stay
 * accurate even without an explicit timer. */
#define MAX_POLL_MS 1000

enum resize_mode {
	RESIZE_COOPERATIVE,
	RESIZE_DELAYED,
	RESIZE_IGNORE,
	RESIZE_EXIT,
	RESIZE_NONE,
};

struct fixture {
	struct wl_display *display;
	struct wl_registry *registry;
	struct wl_compositor *compositor;
	struct wl_shm *shm;
	struct xdg_wm_base *wm_base;
	struct wl_seat *seat;
	uint32_t seat_version;
	struct wl_keyboard *keyboard;
	struct wl_pointer *pointer;

	struct wl_surface *surface;
	struct xdg_surface *xdg_surface;
	struct xdg_toplevel *toplevel;

	struct wl_buffer *buffers[MAX_BUFFERS];
	unsigned int n_buffers;

	/* options */
	const char *title;
	const char *app_id;
	int width;
	int height;
	int frames;
	int period_ms;
	bool animate;
	enum resize_mode resize_mode;
	int resize_delay_ms;
	bool report_input;
	int exit_after_ms;

	/* configure state */
	int configure_count;
	int configured_width;
	int configured_height;
	uint32_t configure_serial;
	bool have_toplevel_configure;
	bool have_surface_configure;
	bool activated;

	/* runtime state */
	bool have_mapped;
	int cur_width;
	int cur_height;
	int frame_count;
	bool animation_done;
	bool resize_seen;
	bool resize_pending;
	int pending_width;
	int pending_height;
	int64_t resize_deadline;
	int64_t grace_deadline;
	int64_t start_ms;
	int64_t last_commit_ms;
	bool done;

	struct wl_callback *frame_callback;
	bool frame_ready;

	/* opt-in input reporting */
	struct xkb_context *xkb_context;
	struct xkb_keymap *xkb_keymap;
	struct xkb_state *xkb_state;
};

/* ------------------------------------------------------------------ util */

static int64_t
now_ms(void)
{
	struct timespec ts;

	clock_gettime(CLOCK_MONOTONIC, &ts);
	return (int64_t) ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

static void
report(const char *fmt, ...)
{
	va_list ap;

	fputs(REPORT_PREFIX, stdout);
	va_start(ap, fmt);
	vfprintf(stdout, fmt, ap);
	va_end(ap);
	fputc('\n', stdout);
	fflush(stdout);
}

static void
fatal(struct fixture *fixture, const char *fmt, ...)
{
	va_list ap;

	(void) fixture;

	fputs(REPORT_PREFIX, stderr);
	va_start(ap, fmt);
	vfprintf(stderr, fmt, ap);
	va_end(ap);
	fputc('\n', stderr);
	exit(EXIT_FAILURE);
}

/* ----------------------------------------------------------------- draw */

static uint32_t
frame_colour(int frame)
{
	/* Knuth multiplicative hash of the frame index; deterministic. */
	return 0xff000000u | ((uint32_t) (frame * 2654435761u) & 0x00ffffffu);
}

static void
paint(uint32_t *pixels, int width, int height, int frame, bool animate)
{
	int rw;
	int rh;
	int span_x;
	int span_y;
	int x0;
	int y0;
	uint32_t colour;
	int x;
	int y;

	for (x = 0; x < width * height; x++)
		pixels[x] = BASE_COLOUR;

	if (!animate)
		return;

	/* One solid rectangle whose position and colour depend only on the
	 * frame index: consecutive animated frames differ byte for byte. */
	rw = width / 4 > 0 ? width / 4 : 1;
	rh = height / 4 > 0 ? height / 4 : 1;
	span_x = width - rw;
	span_y = height - rh;
	x0 = span_x > 0 ? (frame * 37) % span_x : 0;
	y0 = span_y > 0 ? (frame * 23) % span_y : 0;
	colour = frame_colour(frame);

	for (y = y0; y < y0 + rh && y < height; y++)
		for (x = x0; x < x0 + rw && x < width; x++)
			pixels[y * width + x] = colour;
}

static struct wl_buffer *
create_shm_buffer(struct fixture *fixture, int width, int height, int frame)
{
	struct wl_shm_pool *pool;
	struct wl_buffer *buffer;
	uint32_t *pixels;
	int stride = width * 4;
	int size = stride * height;
	int fd;

	fd = memfd_create("wlvision-fixture", MFD_CLOEXEC);
	if (fd < 0)
		fatal(fixture, "memfd_create failed: %s", strerror(errno));
	if (ftruncate(fd, size) < 0)
		fatal(fixture, "ftruncate failed: %s", strerror(errno));

	pixels = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if (pixels == MAP_FAILED)
		fatal(fixture, "mmap failed: %s", strerror(errno));
	paint(pixels, width, height, frame, fixture->animate);
	munmap(pixels, size);

	pool = wl_shm_create_pool(fixture->shm, fd, size);
	buffer = wl_shm_pool_create_buffer(pool, 0, width, height, stride,
					   WL_SHM_FORMAT_XRGB8888);
	wl_shm_pool_destroy(pool);
	close(fd);

	return buffer;
}

static void
frame_done(void *data, struct wl_callback *callback, uint32_t time)
{
	struct fixture *fixture = data;

	(void) time;

	/* Clear the pointer before destroying the proxy: wl_callback_destroy()
	 * would otherwise make the stale pointer look like a live callback. */
	fixture->frame_callback = NULL;
	wl_callback_destroy(callback);
	fixture->frame_ready = true;
}

static const struct wl_callback_listener frame_listener = {
	.done = frame_done,
};

static void
request_frame_callback(struct fixture *fixture)
{
	fixture->frame_callback = wl_surface_frame(fixture->surface);
	wl_callback_add_listener(fixture->frame_callback, &frame_listener,
				 fixture);
}

static void
commit_frame(struct fixture *fixture, int width, int height)
{
	struct wl_buffer *buffer;

	if (fixture->n_buffers == MAX_BUFFERS)
		fatal(fixture, "too many buffers");

	buffer = create_shm_buffer(fixture, width, height, fixture->frame_count + 1);
	fixture->buffers[fixture->n_buffers++] = buffer;

	wl_surface_attach(fixture->surface, buffer, 0, 0);
	wl_surface_damage(fixture->surface, 0, 0, width, height);
	if (!fixture->animation_done && fixture->frame_callback == NULL)
		request_frame_callback(fixture);
	wl_surface_commit(fixture->surface);

	fixture->frame_count++;
	fixture->cur_width = width;
	fixture->cur_height = height;
	fixture->last_commit_ms = now_ms();
	report("committed width=%d height=%d frame=%d", width, height,
	       fixture->frame_count);

	if (fixture->frame_count >= fixture->frames)
		fixture->animation_done = true;
}

/* --------------------------------------------------------- xdg listeners */

static void
wm_base_ping(void *data, struct xdg_wm_base *wm_base, uint32_t serial)
{
	(void) data;
	xdg_wm_base_pong(wm_base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = {
	.ping = wm_base_ping,
};

static void
xdg_surface_configure(void *data, struct xdg_surface *xdg_surface,
		      uint32_t serial)
{
	struct fixture *fixture = data;

	(void) xdg_surface;

	fixture->configure_serial = serial;
	fixture->have_surface_configure = true;
}

static const struct xdg_surface_listener xdg_surface_listener = {
	.configure = xdg_surface_configure,
};

static void
xdg_toplevel_configure(void *data, struct xdg_toplevel *toplevel,
		       int32_t width, int32_t height, struct wl_array *states)
{
	struct fixture *fixture = data;
	uint32_t *state;

	(void) toplevel;

	fixture->configured_width = width;
	fixture->configured_height = height;
	fixture->have_toplevel_configure = true;
	fixture->activated = false;
	wl_array_for_each(state, states) {
		if (*state == XDG_TOPLEVEL_STATE_ACTIVATED)
			fixture->activated = true;
	}
}

static void
xdg_toplevel_close(void *data, struct xdg_toplevel *toplevel)
{
	struct fixture *fixture = data;

	(void) toplevel;
	fixture->done = true;
}

static void
xdg_toplevel_configure_bounds(void *data, struct xdg_toplevel *toplevel,
			      int32_t width, int32_t height)
{
	(void) data;
	(void) toplevel;
	(void) width;
	(void) height;
}

static void
xdg_toplevel_wm_capabilities(void *data, struct xdg_toplevel *toplevel,
			     struct wl_array *capabilities)
{
	(void) data;
	(void) toplevel;
	(void) capabilities;
}

static const struct xdg_toplevel_listener xdg_toplevel_listener = {
	.configure = xdg_toplevel_configure,
	.close = xdg_toplevel_close,
	.configure_bounds = xdg_toplevel_configure_bounds,
	.wm_capabilities = xdg_toplevel_wm_capabilities,
};

/* One surface configure is the pair (xdg_surface.configure with the serial,
 * xdg_toplevel.configure with the size and states).  Act once both halves of
 * the newest pair are in. */
static void
handle_configure(struct fixture *fixture)
{
	int width = fixture->configured_width > 0 ?
		fixture->configured_width : fixture->width;
	int height = fixture->configured_height > 0 ?
		fixture->configured_height : fixture->height;

	fixture->have_surface_configure = false;
	fixture->have_toplevel_configure = false;
	fixture->configure_count++;

	report("configure n=%d width=%d height=%d activated=%s",
	       fixture->configure_count, width, height,
	       fixture->activated ? "yes" : "no");

	xdg_surface_ack_configure(fixture->xdg_surface,
				  fixture->configure_serial);

	/* A window must exist in every mode: the first configure always gets a
	 * matching buffer. */
	if (!fixture->have_mapped) {
		fixture->have_mapped = true;
		commit_frame(fixture, width, height);
		return;
	}

	if (width == fixture->cur_width && height == fixture->cur_height)
		return;

	fixture->resize_seen = true;
	fixture->pending_width = width;
	fixture->pending_height = height;

	switch (fixture->resize_mode) {
	case RESIZE_COOPERATIVE:
	case RESIZE_NONE:
		commit_frame(fixture, width, height);
		break;
	case RESIZE_DELAYED:
		if (fixture->resize_delay_ms <= 0) {
			commit_frame(fixture, width, height);
		} else {
			fixture->resize_pending = true;
			fixture->resize_deadline =
				now_ms() + fixture->resize_delay_ms;
		}
		break;
	case RESIZE_IGNORE:
		/* Acknowledge, but keep the old buffer: never commit a
		 * matching one. */
		break;
	case RESIZE_EXIT:
		/* Destruction during a resize: leave without a new buffer. */
		fixture->done = true;
		break;
	}
}

/* ----------------------------------------------------------- input events */

static void
keyboard_keymap(void *data, struct wl_keyboard *keyboard, uint32_t format,
		int32_t fd, uint32_t size)
{
	struct fixture *fixture = data;
	char *map;

	(void) keyboard;

	if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1 || size == 0) {
		close(fd);
		return;
	}

	map = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
	if (map == MAP_FAILED) {
		close(fd);
		fatal(fixture, "keymap mmap failed: %s", strerror(errno));
	}

	if (fixture->xkb_keymap != NULL)
		xkb_keymap_unref(fixture->xkb_keymap);
	fixture->xkb_keymap = xkb_keymap_new_from_string(
		fixture->xkb_context, map, XKB_KEYMAP_FORMAT_TEXT_V1,
		XKB_KEYMAP_COMPILE_NO_FLAGS);
	munmap(map, size);
	close(fd);

	if (fixture->xkb_keymap == NULL) {
		fputs(REPORT_PREFIX "compositor keymap rejected\n", stderr);
		return;
	}

	if (fixture->xkb_state != NULL)
		xkb_state_unref(fixture->xkb_state);
	fixture->xkb_state = xkb_state_new(fixture->xkb_keymap);
	if (fixture->xkb_state == NULL)
		fatal(fixture, "xkb_state_new failed");
}

static void
keyboard_enter(void *data, struct wl_keyboard *keyboard, uint32_t serial,
	       struct wl_surface *surface, struct wl_array *keys)
{
	(void) data;
	(void) keyboard;
	(void) serial;
	(void) surface;
	(void) keys;
}

static void
keyboard_leave(void *data, struct wl_keyboard *keyboard, uint32_t serial,
	       struct wl_surface *surface)
{
	(void) data;
	(void) keyboard;
	(void) serial;
	(void) surface;
}

static void
keyboard_key(void *data, struct wl_keyboard *keyboard, uint32_t serial,
	     uint32_t time, uint32_t key, uint32_t state)
{
	struct fixture *fixture = data;
	char text[64];
	bool pressed = state == WL_KEYBOARD_KEY_STATE_PRESSED;
	int n = 0;

	(void) keyboard;
	(void) serial;
	(void) time;

	if (fixture->xkb_state != NULL)
		n = xkb_state_key_get_utf8(fixture->xkb_state, key + 8, text,
					   sizeof text);

	report("key keycode=%u state=%s utf8=%s", key,
	       pressed ? "pressed" : "released", n > 0 ? text : "none");

	if (fixture->xkb_state != NULL)
		xkb_state_update_key(fixture->xkb_state, key + 8,
				     pressed ? XKB_KEY_DOWN : XKB_KEY_UP);
}

static void
keyboard_modifiers(void *data, struct wl_keyboard *keyboard, uint32_t serial,
		   uint32_t depressed, uint32_t latched, uint32_t locked,
		   uint32_t group)
{
	struct fixture *fixture = data;

	(void) keyboard;
	(void) serial;

	if (fixture->xkb_state != NULL)
		xkb_state_update_mask(fixture->xkb_state, depressed, latched,
				      locked, 0, 0, group);
}

static void
keyboard_repeat_info(void *data, struct wl_keyboard *keyboard, int32_t rate,
		     int32_t delay)
{
	(void) data;
	(void) keyboard;
	(void) rate;
	(void) delay;
}

static const struct wl_keyboard_listener keyboard_listener = {
	.keymap = keyboard_keymap,
	.enter = keyboard_enter,
	.leave = keyboard_leave,
	.key = keyboard_key,
	.modifiers = keyboard_modifiers,
	.repeat_info = keyboard_repeat_info,
};

static void
pointer_enter(void *data, struct wl_pointer *pointer, uint32_t serial,
	      struct wl_surface *surface, wl_fixed_t sx, wl_fixed_t sy)
{
	(void) data;
	(void) pointer;
	(void) serial;
	(void) surface;
	(void) sx;
	(void) sy;
}

static void
pointer_leave(void *data, struct wl_pointer *pointer, uint32_t serial,
	      struct wl_surface *surface)
{
	(void) data;
	(void) pointer;
	(void) serial;
	(void) surface;
}

static void
pointer_motion(void *data, struct wl_pointer *pointer, uint32_t time,
	       wl_fixed_t sx, wl_fixed_t sy)
{
	(void) pointer;
	(void) time;

	if (((struct fixture *) data)->report_input)
		report("pointer motion x=%d y=%d", sx, sy);
}

static void
pointer_button(void *data, struct wl_pointer *pointer, uint32_t serial,
	       uint32_t time, uint32_t button, uint32_t state)
{
	(void) data;
	(void) pointer;
	(void) serial;
	(void) time;

	report("pointer button button=%u state=%s", button,
	       state == WL_POINTER_BUTTON_STATE_PRESSED ? "pressed" : "released");
}

static void
pointer_axis(void *data, struct wl_pointer *pointer, uint32_t time,
	     uint32_t axis, wl_fixed_t value)
{
	(void) data;
	(void) pointer;
	(void) time;

	report("pointer axis axis=%u value=%d", axis, value);
}

static void
pointer_frame(void *data, struct wl_pointer *pointer)
{
	(void) data;
	(void) pointer;
}

static void
pointer_axis_source(void *data, struct wl_pointer *pointer, uint32_t source)
{
	(void) data;
	(void) pointer;
	(void) source;
}

static void
pointer_axis_stop(void *data, struct wl_pointer *pointer, uint32_t time,
		  uint32_t axis)
{
	(void) data;
	(void) pointer;
	(void) time;
	(void) axis;
}

static void
pointer_axis_discrete(void *data, struct wl_pointer *pointer, uint32_t axis,
		      int32_t discrete)
{
	(void) data;
	(void) pointer;
	(void) axis;
	(void) discrete;
}

static void
pointer_axis_value120(void *data, struct wl_pointer *pointer, uint32_t axis,
		      int32_t value120)
{
	(void) data;
	(void) pointer;
	(void) axis;
	(void) value120;
}

static void
pointer_axis_relative_direction(void *data, struct wl_pointer *pointer,
				uint32_t axis, uint32_t direction)
{
	(void) data;
	(void) pointer;
	(void) axis;
	(void) direction;
}

static const struct wl_pointer_listener pointer_listener = {
	.enter = pointer_enter,
	.leave = pointer_leave,
	.motion = pointer_motion,
	.button = pointer_button,
	.axis = pointer_axis,
	.frame = pointer_frame,
	.axis_source = pointer_axis_source,
	.axis_stop = pointer_axis_stop,
	.axis_discrete = pointer_axis_discrete,
	.axis_value120 = pointer_axis_value120,
	.axis_relative_direction = pointer_axis_relative_direction,
};

static void
seat_capabilities(void *data, struct wl_seat *seat, uint32_t capabilities)
{
	struct fixture *fixture = data;

	if ((capabilities & WL_SEAT_CAPABILITY_KEYBOARD) &&
	    fixture->keyboard == NULL) {
		fixture->keyboard = wl_seat_get_keyboard(seat);
		wl_keyboard_add_listener(fixture->keyboard,
					 &keyboard_listener, fixture);
	}
	if ((capabilities & WL_SEAT_CAPABILITY_POINTER) &&
	    fixture->pointer == NULL) {
		fixture->pointer = wl_seat_get_pointer(seat);
		wl_pointer_add_listener(fixture->pointer, &pointer_listener,
					fixture);
	}
}

static void
seat_name(void *data, struct wl_seat *seat, const char *name)
{
	(void) data;
	(void) seat;
	(void) name;
}

static const struct wl_seat_listener seat_listener = {
	.capabilities = seat_capabilities,
	.name = seat_name,
};

/* ------------------------------------------------------------- registry */

static void
registry_global(void *data, struct wl_registry *registry, uint32_t name,
		const char *interface, uint32_t version)
{
	struct fixture *fixture = data;

	if (strcmp(interface, wl_compositor_interface.name) == 0) {
		fixture->compositor = wl_registry_bind(
			registry, name, &wl_compositor_interface,
			version < 4 ? version : 4);
	} else if (strcmp(interface, wl_shm_interface.name) == 0) {
		fixture->shm = wl_registry_bind(registry, name,
						&wl_shm_interface, 1);
	} else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
		fixture->wm_base = wl_registry_bind(
			registry, name, &xdg_wm_base_interface, 1);
		xdg_wm_base_add_listener(fixture->wm_base, &wm_base_listener,
					 fixture);
	} else if (fixture->report_input &&
		   strcmp(interface, wl_seat_interface.name) == 0) {
		fixture->seat_version = version < 5 ? version : 5;
		fixture->seat = wl_registry_bind(
			registry, name, &wl_seat_interface,
			fixture->seat_version);
		wl_seat_add_listener(fixture->seat, &seat_listener, fixture);
	}
}

static void
registry_global_remove(void *data, struct wl_registry *registry, uint32_t name)
{
	(void) data;
	(void) registry;
	(void) name;
}

static const struct wl_registry_listener registry_listener = {
	.global = registry_global,
	.global_remove = registry_global_remove,
};

/* ------------------------------------------------------------ main loop */

static int
compute_timeout(struct fixture *fixture, int64_t now)
{
	int64_t deadline = INT64_MAX;
	int64_t diff;

	if (fixture->resize_pending && fixture->resize_deadline < deadline)
		deadline = fixture->resize_deadline;
	if (fixture->exit_after_ms > 0 &&
	    fixture->start_ms + fixture->exit_after_ms < deadline)
		deadline = fixture->start_ms + fixture->exit_after_ms;
	if (fixture->grace_deadline != 0 && fixture->grace_deadline < deadline)
		deadline = fixture->grace_deadline;
	if (!fixture->animation_done && fixture->frame_ready &&
	    fixture->last_commit_ms + fixture->period_ms < deadline)
		deadline = fixture->last_commit_ms + fixture->period_ms;

	if (deadline == INT64_MAX)
		return -1;

	diff = deadline - now;
	if (diff < 0)
		diff = 0;
	if (diff > MAX_POLL_MS)
		diff = MAX_POLL_MS;
	return (int) diff;
}

static int
dispatch_once(struct fixture *fixture, int timeout)
{
	struct pollfd pfd;
	int ret;

	while (wl_display_prepare_read(fixture->display) != 0) {
		if (wl_display_dispatch_pending(fixture->display) < 0)
			return -1;
	}

	if (wl_display_flush(fixture->display) < 0 && errno != EAGAIN) {
		wl_display_cancel_read(fixture->display);
		return -1;
	}

	pfd.fd = wl_display_get_fd(fixture->display);
	pfd.events = POLLIN;
	pfd.revents = 0;
	ret = poll(&pfd, 1, timeout);
	if (ret < 0) {
		wl_display_cancel_read(fixture->display);
		return errno == EINTR ? 0 : -1;
	}
	if (ret == 0) {
		wl_display_cancel_read(fixture->display);
	} else if (pfd.revents & POLLIN) {
		if (wl_display_read_events(fixture->display) < 0)
			return -1;
	} else {
		wl_display_cancel_read(fixture->display);
		return -1;
	}

	if (wl_display_dispatch_pending(fixture->display) < 0)
		return -1;
	return 0;
}

static void
run(struct fixture *fixture)
{
	while (!fixture->done) {
		int64_t now = now_ms();

		/* One surface configure is the pair (xdg_surface.configure
		 * with the serial, xdg_toplevel.configure with the size and
		 * states); act once both halves of the newest pair are in. */
		if (fixture->have_surface_configure &&
		    fixture->have_toplevel_configure)
			handle_configure(fixture);

		if (fixture->resize_pending &&
		    now >= fixture->resize_deadline) {
			fixture->resize_pending = false;
			commit_frame(fixture, fixture->pending_width,
				     fixture->pending_height);
		}

		if (fixture->exit_after_ms > 0 &&
		    now - fixture->start_ms >= fixture->exit_after_ms)
			fixture->done = true;

		/* A client whose frame budget is done still waits for the
		 * resize configure its mode depends on; failing that, a short
		 * grace period keeps a compositor that never resizes from
		 * hanging the fixture forever. */
		if (fixture->animation_done && !fixture->resize_seen &&
		    !fixture->resize_pending &&
		    fixture->resize_mode != RESIZE_EXIT) {
			if (fixture->grace_deadline == 0)
				fixture->grace_deadline = now + ANIMATION_GRACE_MS;
			else if (now >= fixture->grace_deadline)
				fixture->done = true;
		}

		/* idle/ignore modes keep the window up quietly; the others are
		 * finished once their resize has settled. */
		if (fixture->animation_done && fixture->resize_seen &&
		    !fixture->resize_pending &&
		    fixture->resize_mode != RESIZE_NONE &&
		    fixture->resize_mode != RESIZE_EXIT)
			fixture->done = true;

		if (fixture->done)
			break;

		now = now_ms();
		if (!fixture->animation_done && fixture->frame_ready &&
		    now >= fixture->last_commit_ms + fixture->period_ms) {
			fixture->frame_ready = false;
			commit_frame(fixture, fixture->cur_width,
				     fixture->cur_height);
		}

		if (dispatch_once(fixture, compute_timeout(fixture, now_ms())) < 0) {
			fprintf(stderr, REPORT_PREFIX
				"display connection lost\n");
			break;
		}
	}
}

/* ------------------------------------------------------------- lifecycle */

static void
usage(const char *argv0)
{
	fprintf(stderr,
		"usage: %s [--title NAME] [--app-id ID] [--width N] [--height N]\n"
		"          [--frames N] [--period MS] [--animate]\n"
		"          [--resize cooperative|delayed|ignore|exit|none]\n"
		"          [--resize-delay MS] [--report-input] [--exit-after MS]\n",
		argv0);
}

static enum resize_mode
parse_resize_mode(const char *value)
{
	if (strcmp(value, "cooperative") == 0)
		return RESIZE_COOPERATIVE;
	if (strcmp(value, "delayed") == 0)
		return RESIZE_DELAYED;
	if (strcmp(value, "ignore") == 0)
		return RESIZE_IGNORE;
	if (strcmp(value, "exit") == 0)
		return RESIZE_EXIT;
	if (strcmp(value, "none") == 0)
		return RESIZE_NONE;
	fprintf(stderr, REPORT_PREFIX "unknown --resize mode '%s'\n", value);
	exit(EXIT_FAILURE);
}

static void
parse_arguments(struct fixture *fixture, int argc, char *argv[])
{
	static const struct option options[] = {
		{ "title", required_argument, NULL, 't' },
		{ "app-id", required_argument, NULL, 'a' },
		{ "width", required_argument, NULL, 'w' },
		{ "height", required_argument, NULL, 'h' },
		{ "frames", required_argument, NULL, 'f' },
		{ "period", required_argument, NULL, 'p' },
		{ "animate", no_argument, NULL, 'A' },
		{ "resize", required_argument, NULL, 'r' },
		{ "resize-delay", required_argument, NULL, 'd' },
		{ "report-input", no_argument, NULL, 'i' },
		{ "exit-after", required_argument, NULL, 'e' },
		{ NULL, 0, NULL, 0 },
	};
	int opt;

	fixture->title = DEFAULT_TITLE;
	fixture->app_id = DEFAULT_APP_ID;
	fixture->width = DEFAULT_WIDTH;
	fixture->height = DEFAULT_HEIGHT;
	fixture->frames = 1;
	fixture->period_ms = 40;
	fixture->animate = false;
	fixture->resize_mode = RESIZE_COOPERATIVE;
	fixture->resize_delay_ms = 300;
	fixture->report_input = false;
	fixture->exit_after_ms = 0;

	while ((opt = getopt_long(argc, argv, "", options, NULL)) != -1) {
		switch (opt) {
		case 't':
			fixture->title = optarg;
			break;
		case 'a':
			fixture->app_id = optarg;
			break;
		case 'w':
			fixture->width = atoi(optarg);
			break;
		case 'h':
			fixture->height = atoi(optarg);
			break;
		case 'f':
			fixture->frames = atoi(optarg);
			break;
		case 'p':
			fixture->period_ms = atoi(optarg);
			break;
		case 'A':
			fixture->animate = true;
			break;
		case 'r':
			fixture->resize_mode = parse_resize_mode(optarg);
			break;
		case 'd':
			fixture->resize_delay_ms = atoi(optarg);
			break;
		case 'i':
			fixture->report_input = true;
			break;
		case 'e':
			fixture->exit_after_ms = atoi(optarg);
			break;
		default:
			usage(argv[0]);
			exit(EXIT_FAILURE);
		}
	}

	if (fixture->width <= 0 || fixture->height <= 0 ||
	    fixture->frames < 0 || fixture->period_ms < 0 ||
	    fixture->resize_delay_ms < 0 || fixture->exit_after_ms < 0) {
		fprintf(stderr, REPORT_PREFIX "invalid numeric argument\n");
		exit(EXIT_FAILURE);
	}
}

int
main(int argc, char *argv[])
{
	struct fixture fixture = { 0 };

	parse_arguments(&fixture, argc, argv);
	fixture.start_ms = now_ms();

	fixture.display = wl_display_connect(NULL);
	if (fixture.display == NULL) {
		fprintf(stderr, REPORT_PREFIX
			"cannot connect to wayland\n");
		return EXIT_FAILURE;
	}
	report("connected");

	fixture.registry = wl_display_get_registry(fixture.display);
	wl_registry_add_listener(fixture.registry, &registry_listener, &fixture);
	if (wl_display_roundtrip(fixture.display) < 0) {
		fprintf(stderr, REPORT_PREFIX "registry roundtrip failed\n");
		return EXIT_FAILURE;
	}

	if (fixture.compositor == NULL || fixture.shm == NULL ||
	    fixture.wm_base == NULL) {
		fprintf(stderr, REPORT_PREFIX "missing globals "
			"(compositor=%p shm=%p xdg_wm_base=%p)\n",
			(void *) fixture.compositor, (void *) fixture.shm,
			(void *) fixture.wm_base);
		return EXIT_FAILURE;
	}

	if (fixture.report_input) {
		if (fixture.seat == NULL) {
			fprintf(stderr, REPORT_PREFIX "missing wl_seat global\n");
			return EXIT_FAILURE;
		}
		fixture.xkb_context = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
		if (fixture.xkb_context == NULL) {
			fprintf(stderr, REPORT_PREFIX
				"xkb_context_new failed\n");
			return EXIT_FAILURE;
		}
	}

	fixture.surface = wl_compositor_create_surface(fixture.compositor);
	fixture.xdg_surface = xdg_wm_base_get_xdg_surface(fixture.wm_base,
							   fixture.surface);
	xdg_surface_add_listener(fixture.xdg_surface, &xdg_surface_listener,
				 &fixture);
	fixture.toplevel = xdg_surface_get_toplevel(fixture.xdg_surface);
	xdg_toplevel_add_listener(fixture.toplevel, &xdg_toplevel_listener,
				  &fixture);
	xdg_toplevel_set_title(fixture.toplevel, fixture.title);
	xdg_toplevel_set_app_id(fixture.toplevel, fixture.app_id);
	wl_surface_commit(fixture.surface);

	run(&fixture);

	/* Let the server observe the last commit; a compositor that vanished
	 * during the run is a normal shutdown, not a fixture failure. */
	if (wl_display_flush(fixture.display) < 0)
		(void) 0;
	if (wl_display_roundtrip(fixture.display) < 0)
		fputs(REPORT_PREFIX "compositor gone before shutdown\n", stderr);

	report("done frames=%d configures=%d", fixture.frame_count,
	       fixture.configure_count);

	if (fixture.frame_callback != NULL)
		wl_callback_destroy(fixture.frame_callback);
	if (fixture.keyboard != NULL)
		wl_keyboard_destroy(fixture.keyboard);
	if (fixture.pointer != NULL)
		wl_pointer_destroy(fixture.pointer);
	if (fixture.seat != NULL)
		wl_seat_destroy(fixture.seat);
	if (fixture.toplevel != NULL)
		xdg_toplevel_destroy(fixture.toplevel);
	if (fixture.xdg_surface != NULL)
		xdg_surface_destroy(fixture.xdg_surface);
	if (fixture.surface != NULL)
		wl_surface_destroy(fixture.surface);
	for (unsigned int i = 0; i < fixture.n_buffers; i++)
		wl_buffer_destroy(fixture.buffers[i]);
	if (fixture.wm_base != NULL)
		xdg_wm_base_destroy(fixture.wm_base);
	if (fixture.shm != NULL)
		wl_shm_destroy(fixture.shm);
	if (fixture.compositor != NULL)
		wl_compositor_destroy(fixture.compositor);
	if (fixture.registry != NULL)
		wl_registry_destroy(fixture.registry);
	wl_display_disconnect(fixture.display);

	if (fixture.xkb_state != NULL)
		xkb_state_unref(fixture.xkb_state);
	if (fixture.xkb_keymap != NULL)
		xkb_keymap_unref(fixture.xkb_keymap);
	if (fixture.xkb_context != NULL)
		xkb_context_unref(fixture.xkb_context);

	return EXIT_SUCCESS;
}
