/*
 * wlvision-shell-client.c - the application side of the shell probe.
 *
 * It creates one xdg_toplevel with a known title and app id, waits for the
 * configure the shell sends, maps a matching shm buffer, then waits for the
 * resize configure and acknowledges it with a matching buffer. Each step is
 * reported on stdout as a "wlvision-client:" line.
 *
 * The xdg-shell bindings are generated by wayland-scanner from
 * wayland-protocols at image build time (see Containerfile); the protocol
 * XML is not hand-rolled.
 *
 * Copyright (C) 2026 wlvision
 * SPDX-License-Identifier: MIT
 */

#define _GNU_SOURCE

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/mman.h>

#include <wayland-client.h>
#include "xdg-shell-client-protocol.h"

#define CLIENT_TITLE  "wlvision-probe-title"
#define CLIENT_APP_ID "wlvision.probe"

#define FALLBACK_WIDTH  200
#define FALLBACK_HEIGHT 150

struct client {
	struct wl_display *display;
	struct wl_registry *registry;
	struct wl_compositor *compositor;
	struct wl_shm *shm;
	struct xdg_wm_base *wm_base;
	struct wl_surface *surface;
	struct xdg_surface *xdg_surface;
	struct xdg_toplevel *toplevel;
	struct wl_buffer *buffers[4];
	unsigned int n_buffers;

	int configured_width;
	int configured_height;
	bool have_toplevel_configure;
	uint32_t configure_serial;
	bool have_surface_configure;

	unsigned int configure_count;
	bool activated;
	bool done;
};

static void
client_report(const char *fmt, ...)
{
	va_list ap;

	fputs("wlvision-client: ", stdout);
	va_start(ap, fmt);
	vfprintf(stdout, fmt, ap);
	va_end(ap);
	fputc('\n', stdout);
	fflush(stdout);
}

static struct wl_buffer *
create_shm_buffer(struct client *client, int width, int height)
{
	struct wl_shm_pool *pool;
	struct wl_buffer *buffer;
	uint32_t *pixels;
	int stride = width * 4;
	int size = stride * height;
	int fd;
	int i;

	fd = memfd_create("wlvision-shell-client", MFD_CLOEXEC);
	if (fd < 0) {
		perror("memfd_create");
		exit(EXIT_FAILURE);
	}
	if (ftruncate(fd, size) < 0) {
		perror("ftruncate");
		exit(EXIT_FAILURE);
	}

	pixels = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if (pixels == MAP_FAILED) {
		perror("mmap");
		exit(EXIT_FAILURE);
	}
	for (i = 0; i < width * height; i++)
		pixels[i] = 0xff204080;
	munmap(pixels, size);

	pool = wl_shm_create_pool(client->shm, fd, size);
	buffer = wl_shm_pool_create_buffer(pool, 0, width, height, stride,
					   WL_SHM_FORMAT_XRGB8888);
	wl_shm_pool_destroy(pool);
	close(fd);

	return buffer;
}

static void
wm_base_ping(void *data, struct xdg_wm_base *wm_base, uint32_t serial)
{
	(void) data;

	xdg_wm_base_pong(wm_base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = {
	.ping = wm_base_ping,
};

static void
xdg_surface_configure(void *data, struct xdg_surface *xdg_surface,
		      uint32_t serial)
{
	struct client *client = data;

	(void) xdg_surface;

	client->configure_serial = serial;
	client->have_surface_configure = true;
}

static const struct xdg_surface_listener xdg_surface_listener = {
	.configure = xdg_surface_configure,
};

static void
xdg_toplevel_configure(void *data, struct xdg_toplevel *toplevel,
		       int32_t width, int32_t height, struct wl_array *states)
{
	struct client *client = data;
	uint32_t *state;

	(void) toplevel;

	client->configured_width = width;
	client->configured_height = height;
	client->have_toplevel_configure = true;
	client->activated = false;

	wl_array_for_each(state, states) {
		if (*state == XDG_TOPLEVEL_STATE_ACTIVATED)
			client->activated = true;
	}
}

static void
xdg_toplevel_close(void *data, struct xdg_toplevel *toplevel)
{
	struct client *client = data;

	(void) toplevel;

	client->done = true;
}

static void
xdg_toplevel_configure_bounds(void *data, struct xdg_toplevel *toplevel,
			      int32_t width, int32_t height)
{
	(void) data;
	(void) toplevel;
	(void) width;
	(void) height;
}

static void
xdg_toplevel_wm_capabilities(void *data, struct xdg_toplevel *toplevel,
			     struct wl_array *capabilities)
{
	(void) data;
	(void) toplevel;
	(void) capabilities;
}

static const struct xdg_toplevel_listener xdg_toplevel_listener = {
	.configure = xdg_toplevel_configure,
	.close = xdg_toplevel_close,
	.configure_bounds = xdg_toplevel_configure_bounds,
	.wm_capabilities = xdg_toplevel_wm_capabilities,
};

static void
registry_global(void *data, struct wl_registry *registry, uint32_t name,
		const char *interface, uint32_t version)
{
	struct client *client = data;

	if (strcmp(interface, wl_compositor_interface.name) == 0) {
		client->compositor =
			wl_registry_bind(registry, name,
					 &wl_compositor_interface,
					 version < 4 ? version : 4);
	} else if (strcmp(interface, wl_shm_interface.name) == 0) {
		client->shm = wl_registry_bind(registry, name,
					       &wl_shm_interface, 1);
	} else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
		client->wm_base =
			wl_registry_bind(registry, name,
					 &xdg_wm_base_interface, 1);
		xdg_wm_base_add_listener(client->wm_base, &wm_base_listener,
					 client);
	}
}

static void
registry_global_remove(void *data, struct wl_registry *registry, uint32_t name)
{
	(void) data;
	(void) registry;
	(void) name;
}

static const struct wl_registry_listener registry_listener = {
	.global = registry_global,
	.global_remove = registry_global_remove,
};

static void
commit_buffer(struct client *client, int width, int height)
{
	struct wl_buffer *buffer;

	/* Buffers stay alive until the client exits: the compositor may still
	 * reference the previous one until the new commit is processed. */
	if (client->n_buffers ==
	    sizeof client->buffers / sizeof client->buffers[0]) {
		fprintf(stderr, "wlvision-client: too many buffers\n");
		exit(EXIT_FAILURE);
	}

	buffer = create_shm_buffer(client, width, height);
	client->buffers[client->n_buffers++] = buffer;

	wl_surface_attach(client->surface, buffer, 0, 0);
	wl_surface_damage(client->surface, 0, 0, width, height);
	wl_surface_commit(client->surface);

	client_report("committed buffer=%dx%d", width, height);
}

int
main(int argc, char *argv[])
{
	struct client client = { 0 };
	int width;
	int height;
	bool reported_activated = false;

	(void) argc;
	(void) argv;

	client.display = wl_display_connect(NULL);
	if (client.display == NULL) {
		fprintf(stderr, "wlvision-client: cannot connect to wayland\n");
		return EXIT_FAILURE;
	}
	client_report("connected");

	client.registry = wl_display_get_registry(client.display);
	wl_registry_add_listener(client.registry, &registry_listener, &client);
	wl_display_roundtrip(client.display);

	if (client.compositor == NULL || client.shm == NULL ||
	    client.wm_base == NULL) {
		fprintf(stderr, "wlvision-client: missing globals "
			"(compositor=%p shm=%p xdg_wm_base=%p)\n",
			(void *) client.compositor, (void *) client.shm,
			(void *) client.wm_base);
		return EXIT_FAILURE;
	}

	client.surface = wl_compositor_create_surface(client.compositor);
	client.xdg_surface =
		xdg_wm_base_get_xdg_surface(client.wm_base, client.surface);
	xdg_surface_add_listener(client.xdg_surface,
				 &xdg_surface_listener, &client);
	client.toplevel = xdg_surface_get_toplevel(client.xdg_surface);
	xdg_toplevel_add_listener(client.toplevel, &xdg_toplevel_listener,
				  &client);
	xdg_toplevel_set_title(client.toplevel, CLIENT_TITLE);
	xdg_toplevel_set_app_id(client.toplevel, CLIENT_APP_ID);
	wl_surface_commit(client.surface);

	while (!client.done) {
		if (wl_display_flush(client.display) < 0) {
			fprintf(stderr, "wlvision-client: flush failed\n");
			return EXIT_FAILURE;
		}
		if (wl_display_dispatch(client.display) < 0) {
			fprintf(stderr, "wlvision-client: dispatch failed\n");
			return EXIT_FAILURE;
		}

		if (!client.have_surface_configure ||
		    !client.have_toplevel_configure)
			continue;

		client.have_surface_configure = false;
		client.have_toplevel_configure = false;
		client.configure_count++;

		width = client.configured_width > 0 ?
			client.configured_width : FALLBACK_WIDTH;
		height = client.configured_height > 0 ?
			client.configured_height : FALLBACK_HEIGHT;

		client_report("configure #%u width=%d height=%d activated=%s",
			      client.configure_count, width, height,
			      client.activated ? "yes" : "no");
		if (client.activated && !reported_activated) {
			reported_activated = true;
			client_report("activated");
		}

		xdg_surface_ack_configure(client.xdg_surface,
					  client.configure_serial);
		commit_buffer(&client, width, height);

		if (width == 640 && height == 480)
			client.done = true;
	}

	/* Make sure the server has processed the last commit before the
	 * process exits (which is what triggers surface_removed). */
	wl_display_roundtrip(client.display);
	client_report("done configures=%u", client.configure_count);

	xdg_toplevel_destroy(client.toplevel);
	xdg_surface_destroy(client.xdg_surface);
	wl_surface_destroy(client.surface);
	for (unsigned int i = 0; i < client.n_buffers; i++)
		wl_buffer_destroy(client.buffers[i]);
	xdg_wm_base_destroy(client.wm_base);
	wl_shm_destroy(client.shm);
	wl_compositor_destroy(client.compositor);
	wl_registry_destroy(client.registry);
	wl_display_disconnect(client.display);

	return EXIT_SUCCESS;
}
